In [1]:
import numpy as np

In [2]:
x=np.array([1,2,3,4,5,6,7])
print(x)

[1 2 3 4 5 6 7]


In [3]:
y=np.array([[1,2,3],[4,5,6]])
y

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
print(y)

[[1 2 3]
 [4 5 6]]


In [5]:
y.shape

(2, 3)

In [10]:
z=np.array([1,2,3,4,5,6,7,8],dtype='int64')

In [7]:
z

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j, 6.+0.j, 7.+0.j, 8.+0.j])

In [11]:
z.strides

(8,)

In [9]:
y.strides

(12, 4)

# Row major and column major

In [19]:
a=np.array([[1,2,3],[4,5,6]],order='F')#column major
           
print(a)
a.strides


[[1 2 3]
 [4 5 6]]


(4, 8)

In [20]:
a=np.array([[1,2,3],[4,5,6]])#Row major
print(a)
a.strides#For memory accessing

[[1 2 3]
 [4 5 6]]


(12, 4)

 **Row major =[1,2,3,4,5,6]. Column major = [1,4,2,5,3,6]**

In [22]:
np.dtype(np.int32)

dtype('int32')

In [28]:
arr=np.array([1,2,3,4,5],dtype='float')
arr

array([1., 2., 3., 4., 5.])

In [31]:
zero=np.zeros((5,2),dtype='int64')
zero

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]], dtype=int64)

In [33]:
one=np.ones((3,3),dtype=int,order='F')
one

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [34]:
one=np.ones((3,3),dtype=int,order='C')
one

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [35]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
np.arange(20,10,-2)

array([20, 18, 16, 14, 12])

In [37]:
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [38]:
np.arange(10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])