In [1]:
import numpy as np

In [3]:
arr1=np.array([[1,2,3],[4,5,6]])

In [4]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
arr2=np.array([[7,8,9],[10,11,12]])

In [6]:
arr2

array([[ 7,  8,  9],
       [10, 11, 12]])

In [7]:
arr=np.concatenate((arr1,arr2),axis=0)

In [8]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [25]:
import numpy as np

arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])

arr2 = np.array([[7, 8, 9],
                 [10, 11, 12]])

# Concatenate along rows
concatenated_arr = np.concatenate((arr1, arr2), axis=1)
print("Concatenated Array along rows:\n",concatenated_arr)

Concatenated Array along rows:
 [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [11]:
arrry=np.concatenate((arr1,arr2))

In [13]:
arrry

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [14]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
import numpy as np

In [16]:
np.random.rand()

0.5124079179709872

In [17]:
np.random.rand(5)

array([0.26823711, 0.75924786, 0.2490486 , 0.55193766, 0.22737403])

In [18]:
np.random.rand(5,3)

array([[0.68635937, 0.3133285 , 0.68566049],
       [0.60215061, 0.06685217, 0.88442434],
       [0.08193562, 0.50692974, 0.2084525 ],
       [0.38747876, 0.95779786, 0.09954404],
       [0.83284538, 0.22868895, 0.03558996]])

In [19]:
np.random.rand(5,3,2)

array([[[0.56240864, 0.99357321],
        [0.7398875 , 0.22533877],
        [0.39687021, 0.92993717]],

       [[0.13609432, 0.03776173],
        [0.72115198, 0.00731711],
        [0.9482068 , 0.64346954]],

       [[0.43062933, 0.19089613],
        [0.90553914, 0.62323807],
        [0.83609609, 0.15621385]],

       [[0.63186758, 0.00442718],
        [0.75736647, 0.42891995],
        [0.00101801, 0.79313953]],

       [[0.03128621, 0.46950375],
        [0.43858992, 0.67875982],
        [0.86713047, 0.37008123]]])

In [20]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [22]:
np.linspace(0,90,10)

array([ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.])

In [26]:
import numpy as np

arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])

arr2 = np.array([[7, 8, 9],
                 [10, 11, 12]])

# Concatenate along rows
concatenated_arr = np.concatenate((arr1, arr2), axis=1)
print("Concatenated Array along rows:\n",concatenated_arr)

Concatenated Array along rows:
 [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [29]:
import numpy as np

# Original 2-D array
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Reshape to 1-D array
reshaped_arr = arr.reshape(-1)
print("Reshaped Array:", reshaped_arr)

Reshaped Array: [1 2 3 4 5 6]


In [30]:
import numpy as np

array1 = np.full((2, 3),80)
print(array1)

[[80 80 80]
 [80 80 80]]


In [31]:
arr2=np.full((5,3),100)
arr2

array([[100, 100, 100],
       [100, 100, 100],
       [100, 100, 100],
       [100, 100, 100],
       [100, 100, 100]])

In [32]:
import numpy as np

# Convert list to array
my_list = [1, 2, 3, 4, 5]
arr_from_list = np.array(my_list)

print("Array from list:",arr_from_list)

Array from list: [1 2 3 4 5]
